@extends('layouts.app')
@section('content')
<style>
	body{
		background-color: #fff;
	}
	h4, h3{
		font-weight: 600;
	}
	p, ul li{
		line-height: 2;
		font-size: 18px;
	}
</style>

<div class="container" style="margin-top: 10rem;"> 
	<div class="row">
		<div class="col-md-12">
			<h1 style="margin-bottom: 30px;"><strong>Privacy Policy for Experlu</strong></h1>

			<p>Experlu Limited. (“Experlu”) provides this Privacy Policy to let you know our policies and procedures regarding the collection, use and disclosure of information through <a href="www.experlu.com">www.experlu.com</a> <b>(the “Site”)</b>, and any other websites, features, applications, widgets or online services that are owned or controlled by Experlu and that post a link to this Privacy Policy (together with the Site, the <b>“Service”</b>), as well as any information Experlu collects offline in connection with the Service. It also describes the choices available to you regarding the use of, your access to, and how to update and correct your personal information. <b>Note that we combine the information we collect from you from the Site, through the Service generally, or offline.</b> </p>

			<p>Please note that certain features or services referenced in this Privacy Policy may not be offered on the Service at all times. Please also review our Terms of Service, which governs your use of the Service.
			We have provided short summaries in this Privacy Policy to help you understand what information we collect, how we use it, and what choices or rights you may have. While these summaries help explain some of the concepts in a simple and clear way, we encourage you to read the entire Privacy Policy to understand our data practices.</p>

			<h3>1. INFORMATION COLLECTION</h3>
			<h4>Users of the Service may be <b>Clients</b> or <b>Experts</b>.</h4>
			<h3><b>Information You Provide to Us</b></h3>

			<p>When you use the Service, you may provide us with information about you. This may include your name and contact information, financial information to make or receive payment for services obtained through the Experlu platform, or information to help us fill out tax forms. When you use the Service, we may also collect information related to your use of the Service and aggregate this with information about other users. This helps us improve our Services for you. You may also provide us with information about your contacts or friends if, for example, you’d like to add those contacts to a message room. Agencies may also provide us with information about Freelancers associated with the Agency.</p>

			<ul>
				<li><strong>Personal Information:</strong> In the course of using the Service (whether as a Client or Freelancer), we may require or otherwise collect information that identifies you as a specific individual and can be used to contact or identify you (“<strong>Personal Information</strong>”). Examples of Personal Information include your name, email address, company address, billing address, and phone number</li>
				<li><strong>Payment Information:</strong> If you use the Service to make or receive payments, we will also collect certain payment information, such as credit card, PayPal or other financial account information, and billing address.</li>
				<li><strong>Identity Verification:</strong> We may collect Personal Information, such as your date of birth or taxpayer identification number, to validate your identity or as may be required by law, such as to complete tax filings. We may request documents to verify this information, such as a copy of your government-issued identification or photo or a billing statement.</li>
				<li><strong>General Audience Service:</strong> The Service is general audience and intended for users 18 and older. We do not knowingly collect Personal Information from anyone younger than age 18. If we become aware that a child younger than 18 has provided us with Personal Information, we will use commercially reasonable efforts to delete such information from our files. If you are the parent or legal guardian of a child younger than age 18 and believe that Experlu has collected Personal Information from your child, please contact us at: <a href="mailto:hello@experlu.com">hello@experlu.com</a>.</li>
				<li><strong>Non-Identifying Information/Usernames:</strong> We also may collect other information, such as post codes, demographic data, information regarding your use of the Service, and general project-related data (“<strong>Non-Identifying Information</strong>”). We may aggregate information collected from Experlu registered and non-registered users (“<strong>Experlu Users</strong>”). We consider usernames to be Non-Identifying Information. Usernames are made public through the Service and are viewable by other Experlu Users.</li>
				<li>In some cases, we may render Personal Information (generally, email address) into a form of Non-Identifying Information referred to in this Privacy Policy as “<strong>Hashed Information</strong>.” This is typically accomplished using a mathematical process (commonly known as a hash function) to convert information into a code. The code does not identify you directly, but it may be used to connect your activity and interests.</li>
				<li><strong>Combination of Personal and Non-Identifying Information:</strong> Certain Non-Identifying Information would be considered a part of your Personal Information if it were combined with other identifiers in a way that enables you to be identified (for example, combining information with your name). But the same pieces of information are considered Non-Identifying Information when they are taken alone or combined only with other non-identifying information (for example, your viewing preferences). We may combine your Personal Information with Non-Identifying Information, but Experlu will treat the combined information as Personal Information.</li>
				<li><strong>•	Collection of Third Party Personal Information:</strong> We collect the following personal information from you about your contacts or friends: First name, last name, and email address when you provide it to us for the purpose of adding your contacts to a message room.</li>
			</ul>

			<p>You do not have a statutory obligation to provide us with any information, but you may have a contractual obligation to do so, and if we do not receive certain information from you, then we will not be able to provide our Service to you. If you have any questions regarding whether provision of information is mandatory and the consequences for withholding such information, please contact us using the contact information below.</p>



			<h4>Information Received from Third Parties</h4>

			<P>Third parties may also give us information about you. If we combine that information with information about you collected through the Service, we will still treat that combined information as set forth in this Privacy Policy.</p>

			<p>We also may receive information about you from third parties. For example, we may supplement the information we collect with outside records or third parties may provide information in connection with a co-marketing agreement or at your request (such as if you choose to sign in with a third-party service). If we combine the information we receive from others with information we collect through the Service, we will treat the combined information as described in this Privacy Policy.</p>


			<h4>Information Collected Automatically</h4>

			<p>Like other online companies, we receive technical information when you use our Services. We use these technologies to analyze how people use our Services, to improve how our Site functions, to save your log-in information for future sessions, and to serve you with advertisements that may interest you.</p>

			<p>We and our third party service providers, including analytics and third party content providers, may automatically collect certain information from you whenever you access or interact with the Service. This information may include, among other information, the browser and operating system you are using, the URL or advertisement that referred you to the Service, the search terms you entered into a search engine that led you to the Service, areas within the Service that you visited, which links you clicked on, which pages or content you viewed and for how long, other similar information and statistics about your interactions, such as content response times, download errors and length of visits to certain pages and other information commonly shared when browsers communicate with websites. We may combine this automatically collected log information with other information we collect about you. We do this to improve services we offer you, and to improve marketing, analytics, and site functionality.</p>
			<p>The information we collect also includes the Internet Protocol (“<strong>IP</strong>”) address or other unique device identifier (“<strong>Device Identifier</strong>”) for any device (computer, mobile phone, tablet, etc.) used to access the Service. A Device Identifier is a number that is automatically assigned or connected to the device you use to access the Service, and our servers identify your device by its Device Identifier. Some mobile service providers may also provide us or our third party service providers with information regarding the physical location of the device used to access the Service.</p>


			<p><strong>Experlu and its partners use cookies or similar technologies to analyse trends, administer the website, track users’ movement around the website and the mobile app, and to gather demographic information about our user base as a whole. The technology used to collect information automatically from Experlu Users may include the following:</strong></p>

			<ul>
				<li><strong>Cookies:</strong> Like many websites, we and our marketing partners, affiliates, analytics, and service providers use “cookies” to collect information. A cookie is a small data file that we transfer to your computer’s hard disk for record-keeping purposes. We use both persistent cookies that remain on your computer or similar device (such as to save your registration ID and login password for future logins to the Service and to track your compliance with the Experlu Terms of Service) and session ID cookies, which expire at the end of your browser session (for example, to enable certain features of the Service, to better understand how Experlu Users interact with the Service and to monitor aggregate usage by Experlu Users and web traffic routing on the Service). You can control the use of cookies at the individual browser level, but if you choose to disable cookies, it may limit your use of certain features or functionality of the Service. </li>
				<li><strong>Web Beacons:</strong> We and our marketing partners, affiliates, analytics, and service providers may also employ software technology known as “web beacons” and/or “tracking tags” to help us keep track of what content on our Service is effective and to serve relevant advertising to you. Web beacons are small graphics with a unique identifier that may be invisible to you, and which are used to track the online activity of Internet users. Web beacons are embedded in the web pages you review or email messages you receive. Web beacons or similar technologies may be used for a number of purposes, including, without limitation, to count visitors to our Service, to monitor how Experlu Users navigate the Service, to count how many emails that were sent were actually opened, or to count how many particular articles or links were actually viewed.</li>
				<li><strong>Embedded Scripts:</strong> We and our marketing partners, affiliates, analytics, and service providers may also employ software technology known as an Embedded Script. An Embedded Script is programming code that is designed to collect information about your interactions with the Service, such as the links you click on. The code is temporarily downloaded onto your computer or other device and is deactivated or deleted when you disconnect from the Service.</li>
			</ul>
			<p>In addition, we and our marketing partners, affiliates, analytics, and service providers may use a variety of other technologies (such as tags) that collect similar information for security and fraud detection purposes and we may use third parties to perform these services on our behalf.</p>

			<h4>HOW WE RESPOND TO DO NOT TRACK SIGNALS</h4>

			<h5>Experlu does not respond to Do-Not-Track signals.</h5>
			<p>Please note that your browser setting may allow you to automatically transmit a “Do Not Track” signal to websites and online services you visit. There is no consensus among industry participants as to what “Do Not Track” means in this context. Like many websites and online services, Experlu does not alter its practices when it receives a “Do Not Track” signal from a visitor’s browser.</p>

			<h4>Client Profiles</h4>

			<p>Experts and clients may create a profile, with certain or all information publicly available. </p>
			<p>
				You may have the opportunity to create a profile, which consists of information about you, and may include Personal Information, photographs, examples of your work, information on work previously performed via the Service and outside the Service, skills, tests taken, test scores, feedback/rating information and other information, including your username (“Profile”). The information in your Profile may be visible to all Experlu Users and the general public subject to the privacy choices you make within your Experlu Profile. You may edit certain information in your Profile via your account and may choose to limit who is able to view certain content you post to your Profile. Clients and Agencies of associated individual users or companies may also have the opportunity to create an organization Profile. If, in any case, you believe that an unauthorized profile has been created about you, you can request for it to be removed by contacting us at <a href="https://experlu.com">https://experlu.com</a> or <a href="mailto:hello@experlu.com">hello@experlu.com</a>.
			</p>
			<h4>Messaging</h4>
			<p>Experts and Clients may communicate with each other through the Service. For example, Experts and Clients may wish to discuss Client needs and proposals. If you communicate with an Client, that Client will also be a “data controller” with respect to such communications.</p>
			<h4>Community Forums</h4>
			<p>We may offer public forums or blogs. If you participate, your comments and questions will be publicly displayed.</p>
			<p>The Service may provide you the opportunity to participate and post content publicly in forums, on blogs, through interactive features on Experlu and through other communication functionality (“<strong>Community Forums</strong>”). You may choose, through such features or otherwise, to submit or post questions, comments, or other content (collectively, “User Forum Content”). Please note that certain information, such as your name and Profile may be publicly displayed on the Service along with your User Forum Content. Please note that your use of Community Forums is subject to the Experlu Forum Rules and our Terms of Service.</p>
			<p><strong>Note that anything you post to a Community Forum is public — others will have access to your User Forum Content and may use it or share it with third parties. If you choose to voluntarily disclose Personal Information in your User Forum Content or use Community Forums to link to your Profile, that information will be considered public information and the protections of this Privacy Policy will not apply.</strong></p>
			<h4>Testimonials</h4>
			
			<p>We display personal testimonials of satisfied customers on our Service, in addition to other endorsements. With your consent we may post your testimonial along with your name. If you wish to update or delete your testimonial, you can contact us at <a href="mailto:hello@experlu.com">hello@experlu.com</a></p>

			<h4>Feedback</h4>
			
			<p>We collect feedback from Experlu Users about their experience with other Experlu Users of our Service. Please note that any feedback you provide via the Service or feedback provided about you is publicly viewable via the Service. On very rare occasions, we may remove feedback pursuant to the relevant provisions of our Terms of Service.</p>

			<h4>Social Networking Services</h4>

			<p>You may register for an account directly with our Site, or through a social networking service. If you register with a social networking service (or later link your account to one), we will collect certain information about you from that social networking service, and what we collect depends on your privacy settings with that social networking service. The Service may also allow you to “like” or share content with social networking services.</p>
			<p>You may register to join the Service directly via the Service or by logging into your account with a third party social networking service (“<strong>SNS</strong>”) via our Service (e.g., Facebook, Github and other third party services that let you sign in using your existing credentials with those services). If you choose to register via an SNS, or to later link your account with the Service to your account with an SNS, we will use the Personal Information you have provided to the SNS (such as your name, email address, gender and other information you make publicly available via the SNS) to create your account. Note that the information we collect from and through an SNS may depend on the privacy settings you have set with the SNS and the permissions you grant to us in connection with linking your account with the Service to your account with an SNS. Other than what we may share with the SNS as described below, the Personal Information an SNS has about you is obtained by the SNS independent of our Service, and Experlu is not responsible for it.</p>
			<p>The Experlu Service also may permit additional interactions between it and a third party website, service, or other content provider, such as enabling you to “like” or share content to a third party SNS. If you choose to “like” or share content, or to otherwise share information from or via our Service with a third party site or service, that information may be publicly displayed, and the third party may have access to information about you and your use of our Service (and we may have access to information about you from that third party). These features may collect your IP address, which page you are visiting on our site, and may set a cookie to enable the feature to function properly. Your interactions with third parties through an SNS or similar features are governed by the respective privacy policies of those third parties.</p>
			<p>You represent that you are entitled to use your SNS account for the purposes described herein without breach by you of any of the terms and conditions that govern the SNS, and without obligating Experlu to pay any fees or making Experlu subject to any usage limitations imposed by such SNS. You can disable the link between your Experlu account and your SNS account at any time through the “Settings” section of our Service. Please note that your relationship with any SNS is governed solely by your agreement(s) with such SNS. If your SNS account terminates, then functions enabled through the link between your Experlu account and your SNS account will terminate as well.
			</p>

			<h3><strong>2. USE OF INFORMATION</strong></h3>
			<p>We use information collected through the Service to provide and improve the Service, process your requests, prevent fraud, provide you with information and advertising that may interest you, comply with the law, and as otherwise permitted with your consent.</p>
			<h3><strong>WE USE INFORMATION WE COLLECT:</strong></h3>
			<ul>
				<li>To provide and improve the Service, complete your transactions, address your inquiries, process your registration, verify the information you provide is valid, and for compliance and internal business purposes.</li>
				<li>To contact you with administrative communications and Experlu newsletters, marketing or promotional materials (on behalf of Experlu or third parties) and other information that may be of interest to you. If you decide at any time that you no longer wish to receive such communications from us, please follow the instructions in the Your Choices and Rights section, below.</li>
				<li>To tailor content we display to you and offers we may present to you, both on the Service and elsewhere online.</li>
				<li>To administer and develop our business relationship with you and, if applicable, the corporation or other legal entity you represent.</li>
				<li>To assess your proposal to perform a job for Experlu and prepare related governmental and internal statistics reports.</li>
				<li>To enforce and comply with the law, including to conduct an investigation, to protect the property and rights of Experlu or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, illegal, fraudulent, unethical or legally actionable activity. We may also use Device Identifiers to identify Experlu Users.</li>
				<li>For the purposes disclosed at the time you provide your information, with your consent, and as further described in this Privacy Policy.</li>
				<p>We use your Personal Information for the purposes described above:</p>
				<li>To Honor Our Contractual Commitments to You. Much of our processing of Personal Information is to meet our contractual obligations to our investors, or to take steps at Users' request in anticipation of entering into a contract with them.</li>
				<li>For Our Legitimate Interests. In many cases, we handle Personal Information on the grounds that it furthers our legitimate interests in commercial activities, such as the following, in ways that are not overridden by the interests or fundamental rights and freedoms of the affected individuals:</li>
				<ul>
					<li>Providing our Site and Service.</li>
					<li>Analyzing and improving our business.</li>
					<li>Communications, including marketing and responding to your inquiries about our services.</li>
					<li>Addressing information security needs and protecting our Users, Experlu, and others.</li>
					<li>Managing legal issues.</li>
				</ul>
				<li>To Comply with Legal Obligations. We need to use and disclose Personal Information in certain ways to comply with our legal obligations.</li>
			</ul>
			<h3><strong>3. DATA RETENTION</strong></h3>

			<p>Unless you request that we delete certain information, we delete the information you submit to verify your identity after 30 days and we retain other information we collect for at least 5 years. Your information may persist in copies made for backup and business continuity purposes for additional time. If you choose to provide us with Personal Information, we encourage you to routinely update the data to ensure that we have accurate and up-to-date information about you.</p>

			<h3><strong>4. INFORMATION SHARING AND DISCLOSURE</strong></h3>

			<p>We may share information about you to provide the Services, for legal and investigative purposes, in connection with sweepstakes and promotions, or if we are part of a merger or acquisition. We may also share non-identifying information with third parties. You have choices as to whether we share your personal information with third parties for their own marketing purposes.</p>
			<p>We may share aggregated Non-Identifying Information and we may otherwise disclose Non-Identifying Information (including, without limitation, Hashed Information) to third parties. We do not share your Personal Information with third parties for those third parties’ marketing purposes unless we first provide you with the opportunity to opt-in to or opt-out of such sharing. We may also share the information we have collected about you, including Personal Information, as disclosed at the time you provide your information, with your consent, as otherwise described in this Privacy Policy, or in the following circumstances:</p>
			<ul>
				<li><strong>Information about Experts shared with Clients, Experlu Payroll Vendors, and Partners: </strong>We share information regarding Experts who have entered into a contract with a Client. Note that if a Expert is suspended from the Experlu Service, we may share that information with Clients for whom that Experlu has worked or submitted proposals for work. If you choose to view a job post or submit a proposal for work as a Expert via the Experlu, we may share relevant information with the applicable Client(s), including, but not limited to, the information contained in your Expert Profile. </li>
				<li><strong>Information about Clients Shared with Experts: </strong>If you have entered into a service contract with another user, we may provide it/him/her with your name, company address, billing address, or tax ID or VAT number in order to complete the transaction or to facilitate the resolution of a claim or dispute. The user receiving your information is not allowed to use it for purposes unrelated to the transaction, such as to contact you for marketing purposes, unless you have expressly consented to it.</li>
				<li><strong>Service Providers: </strong>We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Service-related services (e.g., without limitation, maintenance services, database management, web analytics and online advertising, payment processing, fraud detection and improvement of Experlu’s features) or to assist us in analysing how our Service is used. These third parties may have access to your Personal Information in order to perform these tasks on our behalf.</li>
				<li><strong>What Happens If You Agree to Receive Information from Third Parties or Request that We Share Your Information: </strong>You may be presented with an opportunity to receive information and/or marketing offers from one or more third parties. If you agree at that time to have your Personal Information shared, your Personal Information will be disclosed to that third party (or parties) and will be subject to the privacy policy and practices of that third party. We are not responsible for the privacy policies and practices of third parties, and, if you later decide that you no longer want to receive communications from a third party, you will need to contact that third party directly. You also may request, sometimes through your use of an SNS or similar interactive feature or third party application, that we share information about you with a third party and we will typically do so under those circumstances.</li>
				<li><strong>Legal and Investigative Purposes: </strong>Experlu will share information with government agencies as required by law in response to lawful requests by public authorities, including to meet national security or law enforcement requirements and, including without limitation, in connection with reporting earnings. We cooperate with government and law enforcement officials and private parties to enforce and comply with the law. We will disclose information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate to respond to claims and legal process (including but not limited to subpoenas), or, at the request of governmental authorities or other third parties conducting an investigation where we determine in our sole discretion the disclosure is necessary to (a) protect the property and rights of Experlu or a third party, (b) protect the safety of the public or any person, or (c) prevent or stop activity we may consider to be, or pose a risk of being, illegal, fraudulent, unethical or legally actionable activity. We may also use Device Identifiers to identify Experlu’s Users, and may do so in cooperation with third parties at our discretion.</li>
				<li><strong>Internal and Business Transfers: </strong>Experlu may share information, including Personal Information, with its parent company Experlu Limited, and any current or future subsidiaries or affiliates, primarily for business and operational purposes. We may sell, transfer, or otherwise share some or all of our assets, including your Personal Information, in connection with a merger, acquisition, reorganization or sale of assets (including, in each case, as part of the due-diligence process with any potential acquiring entity) or in the event of bankruptcy.</li>
				<li><strong>Sweepstakes, Contests, and Promotions: </strong>We may offer sweepstakes, contests, and other promotions (any, a “<strong>Promotion</strong>”) that may require registration. By participating in a Promotion, you are agreeing to the official rules that govern that Promotion, which may contain specific requirements of you, including, except where prohibited by law, allowing the sponsor(s) of the Promotion to use your name, voice, likeness, or other indicia of persona in advertising or marketing associated with the Promotion. If you choose to enter a Promotion, your Personal Information may be disclosed to third parties or the public in connection with the administration of such Promotion, including, without limitation, in connection with winner selection, prize fulfilment, and as required by law or permitted by the Promotion’s official rules, such as on a winner’s list.</li>
			</ul>

			<h3><strong>5. THIRD PARTY ANALYTICS PROVIDERS, AD SERVERS AND SIMILAR THIRD PARTIES</strong></h3>
			<p>We may work with advertising agencies and vendors who use technology to help us understand how people use our Site. These vendors may use technologies to serve you advertisements that may interest you. You can choose to opt out of receiving interest-based advertising.</p>
			<p>Experlu works with (or may in the future work with) network advertisers, ad agencies, analytics service providers and other vendors to provide us with information regarding traffic on the Service, including pages viewed and the actions taken when visiting the Service; to serve our advertisements on other websites, within mobile apps and elsewhere online; and to provide us with information regarding the use of the Service and the effectiveness of our advertisements. Our service providers may collect certain information about your visits to and activity on the Service as well as other websites or services, they may set and access their own tracking technologies on your device (including cookies and web beacons), and may use that information to show you targeted advertisements. Some of these parties may collect Personal Information when you visit the Service or other online websites and services. We may also share certain Non-Identifying Information with these parties, including Hashed Information, in connection with the services they provide to us. If you choose to opt out, please note you will continue to receive generic ads.</p>

			<h3><strong>6. YOUR CHOICES AND RIGHTS</strong></h3>
			<p>You have certain choices regarding how we may communicate with you.</p>
			<p>Registered Experlu Users may update their choices regarding the types of communications you receive from us through your online account. You also may opt-out of receiving marketing emails from us by following the opt-out instructions provided in those emails. Please note that we reserve the right to send you certain communications relating to your account or use of the Service (for example, administrative and service announcements) via email and other means and these transactional account messages may be unaffected if you opt-out from receiving marketing communications. You may opt-out of receiving text messages by replying “STOP” to any text message received. Registered Experlu Users who access the Service by using an Experlu mobile application may, with permission, receive push notifications. Similarly, registered Experlu Users who access the Service by using certain desktop browsers may, with permission, receive push notifications. Notification preferences can be modified in the settings menu for the mobile application or the applicable browser.</p>
			<p>All Users may request access to or correction of any Personal Information we have about them or close their account and/or request deletion of all Personal Information we have about them. In certain jurisdictions, Users may have certain rights with regard to their Personal Information. We will honor User requests to the extent we can reasonably do so and as required by law, but some information will remain on the Services, such as information you posted publicly.</p>
			<p>Upon request Experlu will provide you with information about whether we hold any of your personal information. You are responsible for maintaining the accuracy of the information you submit to us, such as your contact information. You may access, correct, or request deletion of your personal information by making updates to that information or by contacting Experlu through your online account. If you request to access all personal information you’ve submitted, we will respond to your request to access within 30 days or as otherwise required by law. If your information is deleted, then your account may become deactivated. If your account is deactivated or you ask to close your account, you will no longer be able to use the Service. If you would like to close your account in our system, you can do so through the Experlu Service.</p>
			<p>Depending on where you are located, you may have certain rights with regard to your Personal Information (including, in certain cases, under the Privacy Shield, described below). For example, if you are located in the European Economic Area (“<strong>EEA</strong>”), in addition to the rights described above, you may contact us at the contact information provided below to (1) request a restriction on the processing of your Personal Information, (2) object to the processing of your Personal Information, or (3) exercise other rights with respect to your Personal Information. Experlu uses or will use an automated means to calculate the Job Success Score of Experts. If you believe that our services have miscalculated your Job Success Score or you would like to exercise any other rights with regard to your Personal Information. We may be able to assist you by conducting a manual review of your Job Success Score, such as by assessing whether the information you’ve provided us is accurate. While we strongly encourage you to first raise any questions or concerns about your Personal Information directly with us, you have a right to lodge a complaint with the relevant supervisory authority and to seek judicial remedy.</p>
			<p>We will use commercially reasonable efforts to honour your requests for deletion; however, certain information will actively persist on the Service even if you close your account, including messages you posted to the Service. In addition, the rights described above may be limited, for example, if fulfilling your request would reveal personal information about another person, or if you ask us to delete information we are required by law to keep or have compelling legitimate interests in keeping (such as for fraud prevention purposes). Your Personal Information may remain in our archives and information you update or delete, or information within a closed account, may persist internally for our administrative purposes, to the extent permitted by law. It is not always possible to completely remove or delete information from our databases. In addition, we typically will not remove information you posted publicly through or on the Service. Bear in mind that neither you nor Experlu can delete all copies of information that has been previously shared with others on the Service.</p>
			<h3><strong>7. SECURITY</strong></h3>
			<p>We take a number of steps to protect your data, but no security is guaranteed.</p>
			<p>Experlu takes commercially reasonable steps to help protect and secure the information it collects and stores about Experlu Users. All access to the Site is encrypted using industry-standard transport layer security technology (“<strong>TLS</strong>”). When you enter sensitive information (such as tax identification number), we encrypt the transmission of that information using secure socket layer technology (“<strong>SSL</strong>”). We also use HTTP strict transport security to add an additional layer of protection for our Experlu Users. But remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. Thus, while we strive to protect your Personal Information, Experlu cannot ensure and does not warrant the security of any information you transmit to us.</p>
			<h3><strong>8. INTERNATIONAL TRANSFER OF PERSONAL INFORMATION</strong></h3>

			<p>Because we are a EU/UK company, we process and store your information in the EU and our service providers may process and store it elsewhere.</p>
			<p>Experlu is a EU company. If you are located outside the EU/UK and choose to provide information to us, Experlu transfers Personal Information to the EU/UK for processing, and our service providers may process Personal Information in the EU/UK and elsewhere. These countries may not have the same data protection laws as the country in which you initially provided the information. When we transfer your information to the United States, we will protect it as described in this Privacy Policy.</p>
			<p>When we transfer Personal Information from territories in the EEA or with similar laws to our affiliates or service providers in the UK and elsewhere outside the EEA, we rely on approved data transfer mechanisms, including standard contractual clauses approved by the European Commission and the Privacy Shield, as described below. You may request a copy of the standard contractual clauses relevant to your Personal Information, if any, using the contact information below.</p>
			<h3><strong>9. LINKS TO OTHER SITES</strong></h3>
			<p>Our Service contains links to other websites. If you choose to click on a third party link, you will be directed to that third party’s website. The fact that we link to a website is not an endorsement, authorization or representation of our affiliation with that third party, nor is it an endorsement of their privacy or information security policies or practices. We do not exercise control over third party websites. These other websites may place their own cookies or other files on your computer, collect data or solicit Personal Information from you. We encourage you to read the privacy policies or statements of the other websites you visit.</p>
			<h3><strong>10. PUBLIC PROFILE</strong></h3>
			<p>The profile you create on our Site will be publicly accessible unless otherwise indicated. You may change the privacy settings of your profile through your account portal.</p>
			<h3><strong>11. PHISHING</strong></h3>
			<p>Phishing websites imitate legitimate websites in order to obtain personal or financial information. Identity theft and the practice currently known as “phishing” are of great concern to Experlu. In addition, if you believe you have received an email or had a similar interaction with a third party pretending to be Experlu, please report it at <a href="https://experlu.com">https://experlu.com</a></p>
			<h3><strong>12. CHANGES TO THIS POLICY</strong></h3>
			<p>We may change this Privacy Policy. If we make material changes, we will provide notice.</p>
			<p>Experlu may update this Privacy Policy at any time and any changes will be effective upon posting. In the event that there are material changes to the way we treat your Personal Information, we will display a notice through the Services prior to the change becoming effective. We may also notify you by email, in our discretion. However, we will use your Personal Information in a manner consistent with the Privacy Policy in effect at the time you submitted the information, unless you consent to the new or revised policy.</p>
			<h3><strong>13. CONTACTING US</strong></h3>
			<p>If you have any questions about this Privacy Policy, please contact us at <a href="https://experlu.com">https://experlu.com</a> or <a href="mailto:hello@experlu.com">hello@experlu.com</a></p>
		</div>
	</div>
</div>
@endsection
@section('script')
@endsection