@extends('layouts.app')
@section('content')
<style>
	body{
		background-color: #fff;
	}
	h4, h3{
		font-weight: 600;
	}
	p, ul li{
		line-height: 2;
		font-size: 18px;
	}
</style>

<div class="container" style="margin-top: 10rem;"> 
	<div class="row">
		<div class="col-md-12">
			<h4><strong>PLEASE READ THE TERMS OF SERVICE CAREFULLY AS THEY CONTAIN IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES, AND OBLIGATIONS. THESE INCLUDE VARIOUS LIMITATIONS AND EXCLUSIONS AND A BINDING ARBITRATION AGREEMENT AND CLASS ACTION WAIVER.</strong></h4>
			<h4>Terms and conditions - Clients</h4>
			<p>Terms of Service - Clients The following Terms of Service, which include the Privacy Policy, IP Policy and any guideline, policy or content displayed on the Website, are a legally binding contractual agreement between you (“User, “you,” “your”, the “Client”) and Experlu (“Experlu,” “we,” “us”) (hereinafter collectively referred to as the “Terms of Service”).  By visiting or using the services available from the domain and sub-domains of <a href="https://www.Experlu.com">https://www.Experlu.com</a> (the “Website”), you agree to be legally bound by these Terms of Service. We reserve the right to revise these Terms of Service and all linked information from time to time in our sole discretion by updating this posting or any linked information. Unless otherwise provided in such revision, the revised terms will take effect when they are posted on the Website.</p>
			<ul>
				<li style="list-style-type: decimal;">Overview and definitions: Experlu is designed to enable anyone seeking professional services like you to submit to us details of matters in respect of which accounting, bookkeeping, tax, audit, payroll or other professional advice and/or assistance and/or services (“Requests for Proposals”) are required and receive responses including proposals from auditors accountants, auditors, tax specialists, bookkeepers and other professionals (“Experts”) with an indication of the fees chargeable by them for their provision of their services and any conditions applicable to those fees (“Proposals”). The Website contains features that enable you to do, among other things, the following: Post jobs, make Requests for Proposals, accept Proposals, communicate with Experts, manage jobs and leave feedback for Experts. We also provide you with certain services described in, and subject to, these Terms of Service (as further defined below, the “Services”). We may add, delete or modify some or all of such Services at any time at our sole discretion with reasonable notice posted in advance on the Website, wherever required or deemed necessary. 
				Experlu is not an accounting, audit, tax or a bookkeeping firm, and we do not provide any audit, accounting, bookkeeping, tax services or professional services or advice. Any such services are provided solely by our Experts and they bear full responsibility for such services. You should in all cases make your own enquiries as to the suitability of any Expert for your particular job. You should not accept a proposal from any Expert without having conducted such checks to your full satisfaction. While our hope is that you will be happy with every Expert you find through Experlu, you should not engage any Expert if you have any doubts or concerns about them. We may include in Experlu information sourced from Experts, including general news and information and profiles of individual Experts. We do not write or control that information and accept no responsibility to you or any person for it. Any information on Experlu is for general guidance only and is not an audit, accounting, tax, bookkeeping or any other professional or non-professional advice. You should take all due care in relying on such information, as this is done at your own risk. Capitalized terms used in these Terms of Service have the following meanings: 
				</li>
				<li style="list-style-type: decimal;">Definitions <br>
				“Account” means the account created by the Website upon registration. 
				“Services” or “Site Services” means, collectively, accepting Requests for Proposals and providing a platform for communication and delivery between you and Experts. 
				“Website” or “Site” means the world wide web site operated by Experlu at https://www.Experlu.com or any replacement URL.
				</li>
				<li style="list-style-type: decimal;">3.	REGISTRATION <br>
					<ul>
						<li style="list-style-type: upper-alpha;">
							Account eligibility <br>
							Experlu offers the Site and Site Services for your business purposes only and not for personal, household, or consumer use. To register for an Account or use the Site and Site Services, you must, and hereby represent that you (a) have or are an employee or agent of and authorized to act for an independent business (whether it be as a self-employed individual/sole proprietor or as a corporation, limited liability company, CIC, charity or other entity); (b) will use the Site and Site Services for business purposes only; (c) will comply with any licensing, registration, or other requirements with respect to your business, or the business for which you are acting, and (d) a legal entity or an individual 18 years or older (or have otherwise reached the age of majority in the jurisdiction in which you conduct business) who can form legally binding contracts. In addition  by joining this Site, you agree to (1) abide by the Terms of Service and the processes, procedures, and guidelines described throughout the Website; (2) be financially responsible for your use of the Website and the purchase or delivery of services; and (3) perform your obligations as specified by any Job Agreement that you accept, unless such obligations are prohibited by law or by the Terms of Service. Experlu reserves the right, in its sole discretion, to refuse, suspend, or terminate Services to anyone or everyone. 
						</li>
						<li style="list-style-type: upper-alpha;">Registration <br>
							You must be a Registered User to use the Service. You are registered upon submission of a Request for Proposal 
						</li>
						<li style="list-style-type: upper-alpha;">Accounts and Profiles <br>
							General. Once you have registered with the Website as a Registered User and requested a Proposal, the Website will create your Account with Experlu. You may create a profile under your Account. Username and Password. During registration, you will be asked to choose a username and password for the Account. As a Registered User, you agree and you are entirely responsible to safeguard and maintain the confidentiality of the username and password you use to access this Website. You authorize Experlu to assume that any person using the Website with your username and password is you or is authorised to act for you. You agree to notify us immediately if you suspect any unauthorized use of the Account.
						</li>
						<li style="list-style-type: upper-alpha;">Account permissions <br>
							You agree not to request or allow another person to create an Account on your behalf, for your use, or for your benefit, except that an authorized employee or agent may create an Account on behalf of your business. By granting other Users permissions under your Account, you represent and warrant that (a) the User is authorized to act on your behalf, (b) you are financially responsible for the User’s actions taken in accordance with those permissions, including, if applicable, entering into binding contracts on behalf of the owner of the Account, and (c) you are fully responsible and liable for any action of any User to whom you have provided any permissions and any other person who uses the Account, including making payments and entering into Job Agreements and the Terms of Service. If any such User violates the Terms of Service, it may affect your ability to use the Site. Upon closure of an Account, Experlu may close any or all related Accounts.
						</li>
						<li style="list-style-type: upper-alpha;">Costs <br>
							Services of Experlu are completely free for its Clients unless otherwise agreed. No costs are involved for Client to use our Website or become a Registered User. Experlu will receive a pre-agreed commission from the Expert.
						</li>
						<p>After engaging with a Expert or receiving a proposal from an Expert, you agree that you or any of your employee, business partner or anyone related to your businesses shall not engage with that or other Experts registered on Experlu, directly or indirectly without obtaining prior written consent from Experlu.</p>
					</ul>
				</li>
				<li style="list-style-type: decimal;">Contractual relationship between Client and Experts
					<ul>
						<li style="list-style-type: upper-alpha;">Proposals <br>
							You may submit a request for Proposals through the Site. We may contact you in order to obtain clarifications regarding the request for Proposals, and such request for Proposal shall be sent to such Experts as determined by Experlu to be appropriate for the relevant job(s). Each of the such Experts shall have the opportunity to submit a Proposal and you shall only receive such number of Proposals as deemed appropriate by Experlu. You can request to meet with potential Experts prior to accepting a Proposal; the format of the meeting shall be determined by Experlu (and may include audio or videoconference).
						</li>
						<li style="list-style-type: upper-alpha;">Acceptance of Proposal and Job Agreement. <br>
							The engagement, contracting and management of a job are between you and each Expert. Upon acceptance of a Proposal, you agree to purchase, and the Expert(s) shall deliver the services and related deliverables in accordance with the following agreements: 
							<ul>
								<li style="list-style-type: lower-alpha;">any agreement between you and the Expert including the Request for proposal and the proposal and other terms and conditions as communicated between you and the Expert on the Website or otherwise, </li>
								<li style="list-style-type: lower-alpha;">these Terms of Service, and </li>
								<li style="list-style-type: lower-alpha;">any engagement agreement between you and the Expert (collectively, the “Job Agreement”). You agree not to enter into any contractual provisions in conflict with these Terms of Service. You are responsible for managing, inspecting, accepting and paying for satisfactory services and deliverables in accordance with the Job Agreement in a timely manner. The Expert is responsible for the performance and quality of the services in accordance with the Job Agreement in a timely manner. You covenant and agree to act with good faith and fair dealing in performance of the Job Agreement.</li>
							</ul>
						</li>
						<li style="list-style-type: upper-alpha;">Independence <br>
							You acknowledge and agree that your relationship with the Expert is that of an independent contractor. The Expert shall perform services as an independent contractor and nothing in these Terms of Service shall be deemed to create a partnership, joint venture, agency, or Client-employee relationship between you and the Expert or between Experlu and you or any Expert. 
						</li>
						<li style="list-style-type: upper-alpha;">General  <br>
							Although Experlu provides a platform for communication and sharing of documents between you and the Expert, Experlu is not a party to the dealing, contracting and fulfilment of any Job between you and an Expert. Experlu has no control over and does not guarantee the quality, safety or legality of any services performed or deliverables created, the truth or accuracy of Job listings, the qualifications, background, or abilities of Registered Users, the ability of Experts to perform services, , or that an Expert can or will actually complete a Job. Experlu is not responsible for and will not control the manner in which an Expert operates and is not involved in the hiring, firing, discipline or working conditions of the Expert. All rights and obligations for the purchase and sale of services or other deliverables are solely between you and each Expert. Other than the Platform, Experlu will not provide any Expert with any materials or tools to complete any Job. Each of You and the Experts must look solely to the other for enforcement and performance of all the rights and obligations arising from Job Agreements and any other terms, conditions, representations, or warranties associated with such dealings. Experlu shall initially grant you access to the Website for the purpose of intermediary services and establishing a Job Agreement between you and an Expert. From the time a Job Agreement is concluded between You and an Expert or either you or the Expert already carries out any assignment, and you share information through the Website within the framework of the concluded Job Agreement, this is no longer the case. From that time Experlu will provide access to the Website exclusively by the Expert’s assignment, in order to support the Expert’s performance of the Job Agreement. With respect to all data (including personal data) processed from the Website, both by You and the Expert, Experlu shall be regarded as a (sub)processor of Expert in the sense of the General Data Protection Regulation Act.

							If, after entering into a Job Agreement with an Expert, you decide to share information with the Expert via the Website (including personal information), the sharing of this information will be based on the Job Agreement between you and the Expert and not on basis of any agreement between you and Experlu. In this case, the Expert is responsible for the data in accordance with applicable privacy laws and regulations and therefore Experlu is a processor of this data of the Expert. Notwithstanding the foregoing, the provisions of these Terms of Service will also apply to the use of the Website for the phase after entering into the Job Agreement.
						</li>
					</ul>
				</li>
				<li style="list-style-type: decimal;">Taxes and benefits. Registered Users and Experts are responsible for payment and reporting of any taxes. You agree that you will abide by any and all applicable statues, regulations and common law. To the extent applicable, Value Added Tax (VAT) shall be payable by Registered Users/ Clients with respect to payments to Experts and Experlu.</li>
				<li style="list-style-type: decimal;">Additional Jobs.  You acknowledge and agree that Experlu may make its platform and the Website available for any future Jobs entered into independently between you and the Expert (“New Jobs”).</li>
				<li style="list-style-type: decimal;">Feedback and user content <br>
					You hereby acknowledge and agree that Registered Users or Clients publish and request Experlu to publish on their behalf information on the Site about the Expert or Client, such as feedback, composite feedback, geographical location, or verification of identity or credentials. However, such information is based solely on unverified data that Experts or Clients voluntarily submit to Experlu and does not constitute and will not be construed as an introduction, endorsement, or recommendation by Experlu; Experlu provides such information solely for the convenience of Users.
				</li>
				<li style="list-style-type: decimal;">You acknowledge and agree that User feedback benefits the marketplace, all Users, and the efficiency of the Site and you specifically request that Experlu post composite or compiled feedback about Users, including yourself, on User Profiles and elsewhere on the Site. You acknowledge and agree that feedback results for you, including your Job Success Score, wherever referenced, and other User Content highlighted by Experlu on the Site or otherwise (“Composite Information”), if any, will include User comments, User ratings, indicators of User satisfaction, and other feedback left exclusively by other Users. You further acknowledge and agree that Experlu will make Composite Information available to other Users, including composite or compiled feedback. Experlu provides its feedback system as a means through which Users can share their opinions of other Users publicly, and Experlu does not monitor, influence, contribute to or censor these opinions. You acknowledge and agree that posted composite or compiled feedback and any other Composite Information relates only to the business advertised in the Profile and not to any individual person. You agree not to use the Composite Information to make any employment, credit, credit valuation, underwriting, or other similar decision about any other User.</li>
				<li style="list-style-type: decimal;">Experlu does not generally investigate any remarks posted by Users or other User Content for accuracy or reliability and does not guarantee that User Content is accurate. You are solely responsible for your User Content, including the accuracy of any User Content, and are solely responsible for any legal action that may be instituted by other Users or third parties as a result of or in connection with your User Content if such User Content is legally actionable or defamatory. Experlu is not legally responsible for any feedback or comments posted or made available on the Site by any Users or third parties, even if that information is defamatory or otherwise legally actionable. In order to protect the integrity of the feedback system and protect Users from abuse, Experlu reserves the right (but is under no obligation) to remove posted feedback or information that, in Experlu’s sole judgment, violates the Terms of Service or negatively affects our marketplace, diminishes the integrity of the feedback system or otherwise is inconsistent with the business interests of Experlu. You acknowledge and agree that you will notify Experlu of any error or inaccurate statement in your feedback results, including the Composite Information, and that if you do not do so, Experlu may rely on the accuracy of such information.</li>
				<li style="list-style-type: decimal;">Termination and suspension  <br>
					<ul>
						<li style="list-style-type: upper-alpha;">These Terms of Service shall become effective as your contractual agreement upon your use of the Website and shall continue until your Account is terminated by you or Experlu as provided for under the terms of this section.</li>
						<li style="list-style-type: upper-alpha;">Unless otherwise agreed to in writing between the parties, either party may terminate the contractual agreement represented by these Terms of Service at any time upon notice to the other party. In such event, your Account is automatically terminated and Experlu shall continue to perform those services necessary to complete any open transaction or conclude any open contracts between you and another Registered User. You can therefore terminate these Terms of Service immediately at any time. You may send your notice by mail to the address of Experlu given in Clause 8 (H) or by email to <a href="mailto:hello@experlu.com">hello@experlu.com</a> </li>
						<li style="list-style-type: upper-alpha;">Any termination of an Account will automatically lead to the termination of all related profiles. </li>
						<li style="list-style-type: upper-alpha;">Without limiting our other remedies, we may issue a warning, or temporarily suspend, indefinitely suspend or terminate your Account or a Job, and refuse to provide any or all services to you if: (1) you breach the letter or spirit of any terms and conditions of these Terms of Service or the linked policies and information incorporated herein by reference, including our written policies and procedures posted on the Website; (2) we are unable to verify or authenticate any information you provide to us; or (3) we believe in our sole discretion that your actions may cause legal liability for you, our Registered Users or for Experlu or are contrary to the interests of the Website. Once indefinitely suspended or terminated, you must not continue to use the Website under the same Account, a different Account, or register under a new Account. </li>
						<li style="list-style-type: upper-alpha;">In addition, violations of these Terms of Service may be prosecuted to the fullest extent of the law and may result in additional penalties and sanctions. </li>
						<li style="list-style-type: upper-alpha;">When your Account is terminated for any reason, you may no longer have access to data, messages, files and other material you keep on the Website. You are at all times responsible for your backup of this information, messages, files and other materials and proposals. Experlu is entitled to remove / destroy this data after termination of your Account. Experlu will inform you two weeks in advance that it will proceed to remove / destroy the data.</li>
					</ul>
				</li>
				<li style="list-style-type: decimal;">Privacy and confidentiality 
					<ul>
						<li style="list-style-type: upper-alpha;">Your use of the Website and the services provided therein and thereby is governed by the terms of these Terms of Service and the Experlu Privacy Policy. It is your responsibility to review the Experlu Privacy Policy, which is incorporated by reference, and we suggest that you review the Privacy Policy and print a copy for yourself. The Privacy Policy is posted on the Website and may be updated from time to time. Unfortunately, we cannot ensure that disclosure of your personal information will not occur in ways not described in the Privacy Policy. We may be required by law to disclose information to government authorities, law enforcement agencies or third parties upon subpoena, and you authorize us to disclose information as we believe, in our sole discretion, is necessary or appropriate. </li>
						<li style="list-style-type: upper-alpha;">The upload of sensitive personal data to the Website is expressly prohibited. Sensitive personal data are data concerning religion or belief, race, political preference, health, sexual orientation, membership of a trade union, criminal records. This also includes copies of a passport or other identification documents. Uploading also refers to listing particular personal information on any communication channel of the Website.</li>
					</ul>
				</li>
				<li style="list-style-type: decimal;">Intellectual Property 
					<ul>
						<li style="list-style-type: upper-alpha;">Experlu Content. Your use of the Website and the services provided therein and thereby is governed by the terms of these Terms of Service and the Experlu IP Policy. It is your responsibility to review the Experlu IP Policy, which is incorporated by reference, and we suggest that you review the IP Policy and print a copy for yourself. The IP Policy is posted on the Website and may be updated from time to time. </li>
						<li style="list-style-type: upper-alpha;">Registered User Content. You are solely responsible for information posted on our Website, including but not limited to <strong>(a)</strong> any audio, video or photographic content (collectively, “Multimedia Content”) and <strong>(b)</strong> any posting or listing made in any public message area, through any email feature or through Experlu’s feedback feature (collectively, “Non-Multimedia Content”) and <strong>(c)</strong> any other content of a personal nature including but not limited to your biography, work history and work product produced for another Registered User including Companies (“Personal Content”). You retain ownership of all Multimedia Content and Personal Content, subject to the licenses granted herein.</li>
					</ul>
				</li>
				<li style="list-style-type: decimal;">You hereby assign to Experlu your rights in any Non-Multimedia Content. At Experlu’s first request, you will immediately and fully, free of charge and unconditionally cooperate in this transfer, in so far as law or regulations impose further conditions on the legal transfer of the Non-Multimedia Content for the fulfillment of which your cooperation is required. You grant us a non-exclusive, worldwide, perpetual, royalty free, irrevocable right to exercise all copyright and publicity rights with respect to the Multimedia Content and to use such Multimedia Content for the purpose of advertising and publicizing Experlu products and services.</li>
				<li style="list-style-type: decimal;">Your information must not: <strong>(a)</strong> infringe any third party’s rights, including but not limited to intellectual property, publicity or privacy; <strong>(b)</strong> be defamatory, trade libelous, threatening or harassing; nor <strong>(c)</strong> be obscene, indecent or contain pornography.</li>
				<li style="list-style-type: decimal;">We do not endorse any information posted by Registered Users and we are not liable for any such information posted on the Website, including but not limited to any information posted about you. We reserve the right to take any action, in our sole discretion, with respect to information posted on the Website which we believe is inappropriate, including but not limited to termination of your Account. However, we cannot, nor do we, control the information provided by you or other Registered Users or other content Experts which is made available through our system.</li>
				<li style="list-style-type: decimal;">Representations, disclaimers, limitations and exclusions 
					<ul>
						<li style="list-style-type: upper-alpha;">Representations and Warranties. You represent, warrant, and agree:
							<ul>
								<li style="list-style-type: lower-roman;">not to grant access to an Account other than to users authorized to act on behalf of the Registered User and only in accordance with these Terms of Service.</li>
								<li style="list-style-type: lower-roman;">to be fully responsible and liable for any action of any user who uses your Account.</li>
								<li style="list-style-type: lower-roman;">not to use your Account, username, or password of another Registered User that you are not expressly authorized to use.</li>
								<li style="list-style-type: lower-roman;">not to allow any third party who is not authorized to do so to use your Account at any time.</li>
								<li style="list-style-type: lower-roman;">not to use any device, software or routine, including but not limited to any viruses, Trojan horses, worms, time bombs, robots or denial-of-service attacks, intended to damage or interfere with the operation of the Website or any transaction being conducted through the Website.</li>
								<li style="list-style-type: lower-roman;">not to intercept or expropriate any system, data or personal information from the Website.</li>
								<li style="list-style-type: lower-roman;">not to take any action that imposes an unreasonable or disproportionately large load on the Website infrastructure, including but not limited to “spam” or other such unsolicited mass emailing techniques.</li>
								<li style="list-style-type: lower-roman;">that you have the right and authority to enter into the Terms of Service and to transact business hereunder.</li>
								<li style="list-style-type: lower-roman;">that you are using the Website solely for the purpose of entering into a bona fide business transaction with other Registered Users.</li>
								<li style="list-style-type: lower-roman;">that they will not use the Website or its services to defraud or mislead any person or entity, including without limitation Experlu or any Register User</li>
								<li style="list-style-type: lower-roman;">that they will not use the Website to violate any law or regulation of England & Wales or any international law or treaty.</li>
							</ul>
						</li>
						<li style="list-style-type: upper-alpha;">Warranty Disclaimer. The services provided by us are provided “as is,” as available, and without any warranties or conditions (express or implied, including the implied warranties of merchantability, accuracy, fitness for a particular purpose, title and non-infringement, arising by statute or otherwise in law or from a course of dealing or usage or trade). we make no representations or warranties, of any kind, either express or implied, as to the quality, identity or reliability of any third party, or as to the accuracy of the postings made on the website by any third party. </li>
						<li style="list-style-type: upper-alpha;">Limitation of Liability. In no event shall we be liable to you or any other registered user for any special, indirect, consequential, incidental or punitive damages pursuant to this agreement, including but not limited to, loss of profits, loss of business opportunities or loss of goodwill, even if advised of the possibility of such damages. notwithstanding any other provision of this agreement, in no event will our liability to you for any action or claim related to the website services provided under these terms of service, whether based on contract, tort, negligence or any other theory of liability, exceed the greater of: (a) GBP 100 or (b) the aggregate amount of monies actually collected by us from you for the services to which the liability relates during the six (6) month period immediately preceding the determination of such liability. such limitation of liability shall not apply if and to the extent any failure or otherwise harmful event was caused by intent or gross negligence on the part of Experlu. </li>
						<li style="list-style-type: upper-alpha;">General Release. If you have a dispute with another Registered User, you release Experlu (and our officers, directors, agents, subsidiaries, joint ventures and employees) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such dispute, unless caused by intent or gross negligence on the part of Experlu</li>
						<li style="list-style-type: upper-alpha;">Indemnity. You agree to defend, hold harmless and indemnify Experlu from and against any and all losses, costs, expenses, damages or other liabilities incurred by Experlu from and against any cost, liability, loss, damage, cause of action, claim, suit, proceeding, demand or action brought by a third party against Experlu: (1) in connection with your use of the Services; or (2) resulting from: (a) your use of the Website, (b) your decision to request Proposals and accept Proposals from Experts; (c) any breach of contract or other claims made by Registered Users with which you conducted business through the Website; (d) your breach of any provision of these Terms of Service; (e) any liability arising from the tax treatment of payments or any portion thereof; (f) any negligent or intentional wrongdoing by any Registered User; (g) any act or omission of yours with respect to the payment of fees to any Expert; (h) your dispute of or failure to pay any Invoice or any other Payment; or (i) your obligations to a Expert. Any such indemnification shall be conditioned on our: (i) notifying you in writing of any such claim, demand, action, cost, liability, loss or threat of any thereof; (ii) cooperating with you in the defence or settlement thereof; and (iii) allowing you to control such defence or settlement. We shall be entitled to participate in such defence through our own counsel at our own cost and expense. We reserve the right to report any wrongdoing of which we become aware to the applicable government agencies or otherwise</li>
						<li style="list-style-type: upper-alpha;">Links. The Website may contain links to third-party web sites not under the control or operation of Experlu. When we provide links, we do so only as a convenience and do not endorse and are not responsible for the content of any linked site or any link contained in a linked site</li>
						<li style="list-style-type: upper-alpha;">Data. You are responsible for creation, storage, and backup of your business records. These Terms of Service and any registration for or subsequent use of this Website will not be construed as creating any responsibility on Experlu’s part to store, backup, retain, or grant access to any information or data for any period</li>
					</ul>
				</li>
				<li style="list-style-type: decimal;">Miscellaneous terms and conditions 
					<ul>
						<li style="list-style-type: upper-alpha;">Compliance with Law. You are responsible for compliance with applicable laws, regulation and treaties, keeping in mind that access to the contents of this Website may not be legal for or by certain persons or in certain countries. </li>
						<li style="list-style-type: upper-alpha;">Modification and Waiver. Experlu will not be considered to have modified or waived any of our rights or remedies under these Terms of Service unless the modification or waiver is in writing and signed by an authorized representative of Experlu. No delay or omission by Experlu in exercising its rights or remedies will impair its rights or be construed as a waiver. Any single or partial exercise of a right or remedy will not preclude further exercise of any other right or remedy.</li>
						<li style="list-style-type: upper-alpha;">Severability. If any part of these Terms of Service is held to be unenforceable, the unenforceable part will be given effect to the greatest extent possible and the remainder will remain in full force and effect. </li>
						<li style="list-style-type: upper-alpha;">Assignment or Transfer. You will not transfer, assign or delegate your rights or obligations (including your Account) under these Terms of Service to anyone without the express written permission of Experlu.</li>
						<li style="list-style-type: upper-alpha;">Experlu may assign these Terms of Service in its sole discretion. </li>
						<li style="list-style-type: upper-alpha;">Force Majeure.  Neither of the parties to these Terms of Service shall be responsible for the failure to perform or any delay in performance of any obligation hereunder due to labour disturbances, accidents, fires, floods, telecommunications or Internet failures, strikes, wars, riots, rebellions, blockades, acts of government, governmental requirements and regulations or restrictions imposed by law or any other similar conditions beyond the reasonable control of such party. The time for performance of such party shall be extended by the period of such delay.</li>
						<li style="list-style-type: upper-alpha;">Notice. All notices required or permitted to be given under these Terms of Service, shall be in writing and shall be deemed to have been duly given if delivered personally or sent by pre-paid telex, telefax or telegram, or mailed first-class, postage pre-paid, by registered or certified mail (notices sent by telex or telefax, or telegram, shall be deemed to have been given on the date sent; those mailed shall be deemed to have been given ten (10) business days after mailing) to the addresses set forth below or to such other address as any party shall designate by notice in writing. If to Experlu: To Experlu address as defined in this article under (H). If to Registered User: To the address associated with Registered User’s access or login information. </li>
						<li style="list-style-type: upper-alpha;">Contact Information Experlu UK Ltd: Legal form: Limited Company with Companies House number: 12314819 Address: 71-75 Shelton Street, Covent Garden, London, England, WC2H 9JQ Telephone: <a href="tel:+44 20 3 983 8100">+44 20 3 983 8100</a> Email: <a href="mailto:help@experlu.com">help@experlu.com</a></li>
						<li style="list-style-type: upper-alpha;">Headings and Labels. The boldface paragraph headings in these Terms of Service are included for ease of reference only and have no binding effect.</li>
						<li style="list-style-type: upper-alpha;">Integration. These Terms of Service and all documents referenced in these Terms of Service (including the policies listed and available by hyperlink) comprise the entire agreement between you and Experlu with respect to the use of this Website and supersede all prior agreements between the parties regarding the subject matter contained herein as well as any conflicting or inconsistent terms in any Website that link to or are linked from the Website.</li>
						<li style="list-style-type: upper-alpha;">Survival. Sections 4, 5, 6, 7 and 8 will survive any termination of these Terms of Service for any reason. </li>
						<li style="list-style-type: upper-alpha;">Complaints. If you have a complaint about Experlu ' service, you may report this by email to help@experlu.com or by mail to the above-mentioned address. We will try to respond to your complaints within 60 days from the date of receipt. In the event that we require a longer period, we will inform you as to when you can expect a more comprehensive reply. We will try to resolve the complaint in consultation with you.</li>
						<li style="list-style-type: upper-alpha;">Applicable law and competent court. This agreement is governed by English law. All disputes arising out of or in connection with this contract shall be submitted exclusively to the competent court in England & Wales. You may also want to review the following: Privacy Policy IP Policy.</li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</div>
@endsection
@section('script')
@endsection